replicaCount: 1

image:
  repository: ghcr.io/softaav325/ai-service
  pullPolicy: IfNotPresent
  tag: "latest"

api:
  port: 8000
  servicePort: 80

ui:
  port: 8501
  servicePort: 8081

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
