FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir pandas scikit-learn joblib

COPY src/ /app/src/

# Настраиваем рабочую директорию для скриптов, чтобы они работали с /data
ENV PYTHONPATH=/app

CMD ["python", "src/train.py"]