apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ml-pipeline-demo
  namespace: demo
spec:
  serviceAccountName: argo-admin
  entrypoint: ml-dag
  # share values
  volumes:
    - name: workdir
      persistentVolumeClaim:
        claimName: argo-pipeline-pvc

  templates:
    - name: ml-dag
      dag:
        tasks:
          - name: generate-data
            template: generate-data-step
          - name: train-model
            dependencies: [generate-data]
            template: train-model-step
          - name: validate-metrics
            dependencies: [train-model]
            template: validate-metrics-step

    - name: generate-data-step
      container:
        image: ml-pipeline-train:v3
        imagePullPolicy: IfNotPresent
        command: [python, /app/src/generate_data.py]
        volumeMounts:
          - name: workdir
            mountPath: /app/data
        workingDir: /app

    - name: train-model-step
      container:
        image: ml-pipeline-train:v3
        imagePullPolicy: IfNotPresent
        command: [python, /app/src/train.py]
        volumeMounts:
          - name: workdir
            mountPath: /app/data
        workingDir: /app

    - name: validate-metrics-step
      container:
        image: ml-pipeline-train:v3
        imagePullPolicy: IfNotPresent
        command: [ls, -R, /app/data]
        volumeMounts:
          - name: workdir
            mountPath: /app/data
        workingDir: /app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  namespace: demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-admin-role
  namespace: demo
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflows/finalizers", "workflowtasksets", "workflowtaskresults"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-admin-binding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: argo-admin
    namespace: demo
roleRef:
  kind: Role
  name: argo-admin-role
  apiGroup: rbac.authorization.k8s.io