apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-service
  namespace: default  # where object Application

spec:
  project: default

  source:
    repoURL: https://github.com/softaav325/argo-mlops.git
    targetRevision: main
    path: k8s/charts/ai-service

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ai-service  # where Argo CD deployed app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true