apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-service.fullname" . }}-ui
spec:
  type: NodePort
  selector:
    {{- include "ai-service.selectorLabels" . | nindent 4 }}
    app: ui
  ports:
    - protocol: TCP
      port: {{ .Values.ui.servicePort }}
      targetPort: {{ .Values.ui.port }}
      nodePort: 30080
