name: Simple CI

on: # когда запускать workflow
  push:
    branches: [ main ]
  pull_request:

jobs: # список задач
  build-and-test:
    runs-on: ubuntu-latest # какой runner использовать
    timeout-minutes: 20

    steps: # шаги выполнения  
      - name: Checkout code # название шага
        uses: actions/checkout@v4 # какой action использовать

      - name: Setup Node.js
        uses: actions/setup-node@v4 # какой action использовать
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build